const servicesData = [
    {
        "id": "diseno-locales-guayaquil",
        "title": "Diseño y Renders de Locales en Guayaquil | Render 3D Global",
        "metaDescription": "Diseño de interiores comerciales en Guayaquil. Renders para franquicias y locales en samborondón y via a la costa. Aprobación municipal y centros comerciales.",
        "h1": "Diseño y Renders de Locales en Guayaquil",
        "subtitle": "Lanza o renueva tu marca en los mejores centros comerciales del Ecuador.",
        "alertText": "Expertos en visualización retail 3D. Renders funcioanles para nuevos locales en todo lugar, desde el Mall del Sol, San Marino, Riocentro hasta el Millenium Plaza.",
        "seoHiddenText": "Servicio de <strong>renders de locales comerciales</strong> en Guayaquil y Samborondón. Diseño de vitrinas, puntos de venta e islas para centros comerciales. Visualización arquitectónica para franquicias. Aprobación de proyectos retail.",
        "mainImageUrl": "../assets/projects/render-concesionario-chevrolet/render-concesionario-chevrolet-recepcion.webp",
        "mainImageAlt": "Locales Comerciales Guayaquil",
        "leftTitle": "Potencia tu Marca",
        "benefits": [
            "Visualización de iluminación.",
            "Recorridos virtuales para aprobación de marca.",
            "Renders nocturnos y diurnos.",
            "Integración de mobiliario comercial."
        ],
        "rightTitle": "¿Abriendo nuevo local?",
        "rightText": "Asegura la aprobación de la administración.",
        "ctaText": "Cotizar Retail Design",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, cotización local comercial Ecuador"
    },
    {
        "id": "diseno-stands-corferias",
        "title": "Diseño y Render de Stands para Corferias | Render 3D Global",
        "metaDescription": "Diseñador de stands para ferias en Corferias Bogotá. Renders impactantes para aprobación y montaje. Destaque su marca.",
        "h1": "Diseño y Render de Stands para Corferias",
        "subtitle": "Llega a Corferias con un diseño ganador. Visualización de alto impacto para ferias y exposiciones.",
        "alertText": "Conocemos los estándares de montaje. Renders que te ayudan a ganar la licitación y asegurar el mejor espacio.",
        "seoHiddenText": "Servicio de <strong>diseño de stands 3D</strong> para ferias en Bogotá (Corferias). Renders para Expocamacol, Feria del Hogar, FILBo y eventos corporativos. Diseño de arquitectura efímera, kioscos y puntos de venta. Visualización para montaje de eventos y escenografía.",
        "mainImageUrl": "../assets/projects/diseno-render-stand-feria-comercial/diseno-render-stand-feria-comercial-02.webp",
        "mainImageAlt": "Diseño Stand Corferias",
        "leftTitle": "Servicios para Expositores",
        "benefits": [
            "Propuestas de diseño innovadoras y funcionales.",
            "Renders de alta resolución para aprobación interna.",
            "Renders que sirven como guía visual para los montadores.",
            "Adaptación estricta a la identidad de tu marca."
        ],
        "rightTitle": "¿Se acerca la feria?",
        "rightText": "Tenemos tiempos de entrega express para licitaciones.",
        "ctaText": "Cotizar Stand",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, necesito un stand para feria"
    },
    {
        "id": "recorridos-virtuales-360",
        "title": "Recorridos Virtuales 360Â° | Render 3D Global",
        "metaDescription": "Recorridos virtuales interactivos 360 para inmobiliarias y arquitectura. Tours virtuales para venta de proyectos sobre planos.",
        "h1": "Recorridos Virtuales 360Â°",
        "subtitle": "Lleva a tu cliente dentro del proyecto. Permite que explore cada rincón de forma interactiva.",
        "alertText": "La herramienta definitiva para ventas inmobiliarias a distancia o presentaciones de alto impacto, visible desde celular o computador.",
        "seoHiddenText": "Servicio de <strong>tours virtuales 360</strong> y realidad virtual para arquitectura. Recorridos interactivos para inmobiliarias y salas de venta digitales. Visualización panorámica inmersiva para venta de apartamentos sobre planos. Experiencia de usuario interactiva para presentación de proyectos.",
        "mainImageUrl": "../assets/projects/render-oficina-flexible-auditorio-salas/render-oficina-flexible-auditorio-salas-01.webp",
        "mainImageAlt": "Tour 360",
        "leftTitle": "La experiencia de venta más inmersiva",
        "benefits": [
            "Experiencia interactiva total para el usuario.",
            "Compatible con gafas VR, móviles y tablets.",
            "Ideal para preventa de apartamentos modelo.",
            "Muestra áreas comunes y zonas sociales completas."
        ],
        "rightTitle": "¿Quieres impactar a tus inversores?",
        "rightText": "Haz que caminen por tu proyecto antes de construirlo.",
        "ctaText": "Cotizar Recorrido",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, quisiera más información sobre recorridos virtuales"
    },
    {
        "id": "render-cocinas-bogota",
        "title": "Renders de Cocinas Integrales en Bogotá | Render 3D Global",
        "metaDescription": "Cotiza tu render de cocina integral en Bogotá. Visualización 3D fotorrealista para fabricantes de cocinas y remodelaciones. Precios competitivos.",
        "h1": "Renders de Cocinas Integrales en Bogotá",
        "subtitle": "La mejor herramienta de venta para fabricantes de cocinas y carpinteros.",
        "alertText": "Diseña, visualiza y vende más rápido mostrando a tu cliente exactamente cómo quedará su cocina antes de cortar la primera tabla.",
        "seoHiddenText": "Ofrecemos <strong>renders de cocinas integrales</strong> en Bogotá y todo Colombia. Servicio de diseño 3D para carpinterías y fábricas de muebles. Visualización de materiales, granitos, mármoles y acabados en melamina. Precios especiales por volumen para empresas de cocinas.",
        "mainImageUrl": "../assets/projects/render-apartamento-moderno-interior/render-apartamento-moderno-interior-07.webp",
        "mainImageAlt": "Render Cocina Integral",
        "leftTitle": "Ventajas para Fabricantes",
        "benefits": [
            "Acelera la decisión de compra del cliente.",
            "Evita cambios costosos durante la instalación.",
            "Muestra opciones de colores y herrajes al instante.",
            "Presentaciones profesionales con tu logo."
        ],
        "rightTitle": "¿Necesitas cotizar un render?",
        "rightText": "Enviamos cotización en menos de 2 horas.",
        "ctaText": "Cotizar Cocina 3D",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, necesito cotizar una cocina 3D"
    },
    {
        "id": "render-conjuntos-cerrados",
        "title": "Cotización de Renders para Conjuntos Cerrados | Render 3D Global",
        "metaDescription": "Renders para ventas de conjuntos residenciales y urbanismo. Visualización de casas, zonas comunes y fachadas para constructoras.",
        "h1": "Cotización de Renders para Conjuntos Cerrados",
        "subtitle": "Visualización arquitectónica profesional para venta de proyectos inmobiliarios sobre planos.",
        "alertText": "Asegura el éxito en ventas de tu proyecto residencial con imágenes 3D de alta calidad que emocionen a tus compradores.",
        "seoHiddenText": "Servicio de <strong>renders para conjuntos residenciales</strong>, condominios y urbanizaciones. Cotización rápida para constructoras e inmobiliarias. Renders de fachadas, zonas comunes, porterías, piscinas y zonas verdes. Videos y recorridos virtuales 3D para sala de ventas.",
        "mainImageUrl": "../assets/projects/visualizacion-paisajismo-jardines-exteriores/visualizacion-paisajismo-jardines-exteriores-04.webp",
        "mainImageAlt": "Render Conjunto Cerrado",
        "leftTitle": "Pack Completo para Constructoras",
        "benefits": [
            "Renders exteriores de casas tipo y torres.",
            "Visualización de zonas sociales (Salón, BBQ, Piscina).",
            "Recorridos virtuales 360 para sala de ventas.",
            "Planos comerciales ambientados (Plantas 3D)."
        ],
        "rightTitle": "¿Lanzamiento del proyecto pronto?",
        "rightText": "Trabajamos bajo presión para cumplir tus fechas.",
        "ctaText": "Solicitar Presupuesto",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, me interesa una cotización para un conjunto"
    },
    {
        "id": "render-precio-ecuador",
        "title": "Precios de Renders 3D en Ecuador | Render 3D Global",
        "metaDescription": "Cotización de renders arquitectónicos en Ecuador. Tarifas de visualización 3D para Quito, Guayaquil, Cuenca y Manta. Excelente relación calidad-precio.",
        "h1": "Precios de Renders 3D en Ecuador",
        "subtitle": "Calidad internacional a precios competitivos. Optimiza tu presupuesto sin sacrificar el impacto visual.",
        "alertText": "Entiende cómo se cotiza tu proyecto. Factores que influyen: complejidad, número de imágenes y tiempo de entrega. Atendemos arquitectos de todo el Ecuador.",
        "seoHiddenText": "Ofrecemos <strong>tarifas de renders 3D</strong> transparentes para arquitectos y constructores en Ecuador. Paquetes de visualización para proyectos inmobiliarios. Cotización render interior, exterior y recorrido virtual. Descuentos por volumen para conjuntos habitacionales y torres.",
        "mainImageUrl": "../assets/projects/render-oficina-flexible-auditorio-salas/render-oficina-flexible-auditorio-salas-01.webp",
        "mainImageAlt": "Precios Render Ecuador",
        "leftTitle": "¿Cuánto cuesta un Render?",
        "benefits": [
            "Precios flexibles según la escala del proyecto.",
            "Paquetes económicos para remodelaciones.",
            "Render express: Calidad rápida a buen precio."
        ],
        "rightTitle": "Solicita tu Cotización Personalizada",
        "rightText": "Recibe una propuesta detallada hoy mismo.",
        "ctaText": "Consultar Tarifas",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, quisiera saber precios de renders"
    },
    {
        "id": "render-remodelacion-oficinas-samborondon",
        "title": "Renders para Remodelación de Oficinas en Samborondón | Render 3D Global",
        "metaDescription": "Diseño de oficinas corporativas en Samborondón. Renders para remodelación de espacios de trabajo en Plaza Lagos, Xima y La Puntilla. Optimización de espacios.",
        "h1": "Renders para Remodelación de Oficinas en Samborondón",
        "subtitle": "Transforma espacios corporativos. Visualización 3D para oficinas en Plaza Lagos, Xima y La Puntilla.",
        "alertText": "Diseño interior corporativo de alto nivel. Muestra a tus clientes cómo quedará su nueva oficina antes de iniciar la obra.",
        "seoHiddenText": "Especialistas en <strong>renders de oficinas</strong> para empresas en Samborondón y Guayaquil. Diseño de recepción, sala de juntas y espacios de coworking. Visualización para remodelación de locales en edificios corporativos. Optimización de espacios de trabajo.",
        "mainImageUrl": "../assets/projects/render-oficina-flexible-auditorio-salas/render-oficina-flexible-auditorio-salas-08.webp",
        "mainImageAlt": "Oficinas Samborondón",
        "leftTitle": "Soluciones Corporativas",
        "benefits": [
            "Visualización de mobiliario ergonómico.",
            "Iluminación y acabados.",
            "Renders 360 para aprobación gerencial.",
            "Entrega rápida para cumplir cronogramas."
        ],
        "rightTitle": "¿Remodelando la oficina?",
        "rightText": "Visualiza el cambio antes de invertir.",
        "ctaText": "Cotizar Diseño de Oficina",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, cotización remodelación oficina"
    },
    {
        "id": "renders-express-para-stands-comerciales",
        "title": "Renders de Stands Comerciales | Render 3D Global",
        "metaDescription": "Gana licitaciones con renders de stands impactantes. Visualización 3D express para ferias y centros comerciales.",
        "h1": "Renders para Stands Comerciales",
        "subtitle": "Gana tu lugar en la feria. Presenta una imagen profesional que destaque sobre la competencia.",
        "alertText": "Ideal para propuestas urgentes donde necesitas una aprobación rápida para empezar a fabricar.",
        "seoHiddenText": "Especialistas en <strong>renders para stands de ferias</strong> y kioscos en centros comerciales. Visualización 3D express para licitaciones y concursos. Diseño de stands publicitarios y arquitectura efímera. Renders de alta calidad para ventas y aprobación de marca en espacios comerciales.",
        "mainImageUrl": "../assets/projects/diseno-render-stand-feria-comercial/diseno-render-stand-feria-comercial-02.webp",
        "mainImageAlt": "Stand Comercial",
        "leftTitle": "Por qué nuestros renders ganan concursos",
        "benefits": [
            "Iluminación estratégica para destacar la marca.",
            "Vistas aéreas y peatonales para entender el flujo.",
            "Aplicación precisa de branding y logotipos.",
            "Entregas express para cumplir con fechas límite."
        ],
        "rightTitle": "¿Tienes una licitación urgente?",
        "rightText": "No pierdas la oportunidad por falta de visualización.",
        "ctaText": "Cotizar Stand Express",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, necesito un render para un stand"
    },
    {
        "id": "renders-flipping-inmobiliario",
        "title": "Renders para Flipping Inmobiliario | Render 3D Global",
        "metaDescription": "Vende tu proyecto de flipping antes de terminar la obra. Renders de remodelación para inversionistas inmobiliarios en Colombia.",
        "h1": "Renders para Flipping Inmobiliario en Colombia",
        "subtitle": "Vende sobre planos antes de terminar la remodelación. Maximiza tu retorno de inversión.",
        "alertText": "El secreto del flipping exitoso es la velocidad. Publica tu propiedad con imágenes de lujo mientras los obreros aún están trabajando.",
        "seoHiddenText": "Especialistas en <strong>renders para flipping inmobiliario</strong> y remodelación de apartamentos para reventa. Visualización rápida para inversionistas de bienes raíces. Renders de home staging virtual. Acelera la venta de propiedades remodeladas en Bogotá, Medellín y Cali.",
        "mainImageUrl": "../assets/projects/render-apartamento-moderno-interior/render-apartamento-moderno-interior-08.webp",
        "mainImageAlt": "Flipping Inmobiliario",
        "leftTitle": "Herramientas para Inversionistas",
        "benefits": [
            "Render \"Antes y Después\" para atraer compradores.",
            "Home Staging Virtual para espacios vacíos.",
            "Recorrido virtual para pre-venta.",
            "Costo bajo para maximizar tu margen."
        ],
        "rightTitle": "¿Quieres vender rápido?",
        "rightText": "No esperes a que termine la obra para venderla.",
        "ctaText": "Cotizar Render Express",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, me interesa un render para flipping"
    },
    {
        "id": "renders-optimizacion-espacios",
        "title": "Renders para Optimización de Espacios | Render 3D Global",
        "metaDescription": "Maximiza cada metro cuadrado con distribución 3D. Renders para validar aforo y mobiliario en oficinas y viviendas compactas.",
        "h1": "Renders para Optimización de Espacios",
        "subtitle": "Maximiza cada m². Demuestra que el mobiliario cabe perfectamente antes de iniciar la mudanza.",
        "alertText": "Perfecto para oficinas, coworking o viviendas compactas donde cada centímetro cuenta y el flujo debe ser perfecto.",
        "seoHiddenText": "Servicio de <strong>distribución de espacios 3D</strong> y layout comercial. Visualización para oficinas open space y coworking. Renders para validar aforo y mobiliario en plantas arquitectónicas. Optimización de área vendible para inmobiliarias y constructores.",
        "mainImageUrl": "../assets/projects/render-interiorismo-oficinas-modernas/render-interiorismo-oficinas-modernas-03.webp",
        "mainImageAlt": "Optimización Espacios",
        "leftTitle": "Ahorra errores costosos de distribución",
        "benefits": [
            "Verificación de distancias de circulación.",
            "Validación de capacidad máxima de personas.",
            "Distribución eficiente de estaciones de trabajo.",
            "Pruebas de zonificación para diferentes usos."
        ],
        "rightTitle": "¿Necesitas reubicar una oficina?",
        "rightText": "Asegura que todo encaje antes de mover un solo mueble.",
        "ctaText": "Cotizar Distribución",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, necesito optimizar un espacio"
    },
    {
        "id": "visualizacion-arquitectonica-para-contratistas",
        "title": "Renders para Remodelaciones y Adecuaciones | Render 3D Global",
        "metaDescription": "Ayuda visual para contratistas y maestros de obra. Explica remodelaciones y acabados con imágenes claras.",
        "h1": "Renders para Remodelaciones y Adecuaciones",
        "subtitle": "Cierra el trato sin planos confusos. Deja de explicar medidas difíciles de entender.",
        "alertText": "Muestra la foto de cómo quedará la obra terminada para que tu cliente firme el presupuesto con total confianza.",
        "seoHiddenText": "Servicio de visualización para <strong>contratistas y constructores</strong>. Renders de antes y después para remodelaciones. Vende reformas con imágenes claras en lugar de planos técnicos. Apoyo visual para presupuestos de obra civil, remodelación de cocinas, baños y fachadas.",
        "mainImageUrl": "../assets/projects/render-interiorismo-oficinas-modernas/render-interiorismo-oficinas-modernas-04.webp",
        "mainImageAlt": "Remodelación",
        "leftTitle": "La solución para evitar malentendidos",
        "benefits": [
            "\"Antes y después\" para impactar al cliente.",
            "Validación de materiales (enchapes, pintura, pisos).",
            "Visualización de cocinas y baños reformados.",
            "Herramienta de venta para justificar el presupuesto."
        ],
        "rightTitle": "¿Tienes una obra pendiente?",
        "rightText": "Ayuda a tu cliente a decidirse mostrándole el resultado.",
        "ctaText": "Cotizar Render de Obra",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, quisiera cotizar un render de remodelación"
    },
    {
        "id": "visualizacion-paisajismo-jardines-exteriores",
        "title": "Proyección sobre Entorno Existente | Render 3D Global",
        "metaDescription": "Fotomontaje arquitectónico y renders sobre fotografía real. Visualiza paisajismo y remodelaciones sin modelado complejo.",
        "h1": "Proyección sobre Entorno Existente",
        "subtitle": "Visualiza cambios sobre fotos reales. Ideal para propuestas de paisajismo, acabados de fachada o remodelaciones puntuales.",
        "alertText": "Logra aprobaciones inmediatas mostrando el potencial final sobre la situación actual, sin necesidad de modelado complejo.",
        "seoHiddenText": "Servicio de <strong>fotomontaje arquitectónico</strong> y superposición 3D. Renders sobre fotografía existente para paisajismo, renovación de fachadas y urbanismo táctico. Antes y después visual sin modelado completo. Visualización de impacto visual para proyectos urbanos.",
        "mainImageUrl": "../assets/projects/visualizacion-paisajismo-jardines-exteriores/visualizacion-paisajismo-jardines-exteriores-04.webp",
        "mainImageAlt": "Proyección Paisajismo",
        "leftTitle": "Ventajas del Fotomontaje",
        "benefits": [
            "Costo eficiente al no modelar todo el entorno.",
            "Realismo máximo al integrar con el contexto real.",
            "Perfecto para intervenciones puntuales en fachadas.",
            "Comparativa directa con el estado actual."
        ],
        "rightTitle": "¿Tienes una foto de tu proyecto?",
        "rightText": "Déjanos mostrarte cómo puede quedar.",
        "ctaText": "Cotizar Proyección",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, quisiera cotizar un fotomontaje"
    },
    {
        "id": "visualizacion-para-disenadores-interiores",
        "title": "Diseño de Interiores | Render 3D Global",
        "metaDescription": "Valida tus propuestas de diseño interior con renders rápidos. Iluminación, texturas y mobiliario real.",
        "h1": "Diseño de Interiores",
        "subtitle": "Muestra el resultado antes de comprar. Evita dudas y cambios costosos durante la obra.",
        "alertText": "La herramienta perfecta para diseñadores que quieren validar sus ideas y enamorar a sus clientes.",
        "seoHiddenText": "Servicio de <strong>renders de interiorismo</strong> y decoración. Visualización 3D para diseñadores de interiores y arquitectos. Imágenes fotorrealistas de salas, comedores, cocinas y habitaciones. Catálogo de mobiliario 3D y texturas reales. Presentación de proyectos de diseño interior.",
        "mainImageUrl": "../assets/projects/render-interiorismo-oficinas-modernas/render-interiorismo-oficinas-modernas-01.webp",
        "mainImageAlt": "Diseño de Interiores",
        "leftTitle": "Beneficios para Diseñadores",
        "benefits": [
            "Validación de iluminación y atmósfera.",
            "Pruebas de combinación de texturas y colores.",
            "Catálogo amplio de mobiliario y decoración.",
            "Vistas de detalle para acabados complejos."
        ],
        "rightTitle": "¿Listo para presentar tu propuesta?",
        "rightText": "Sorprende a tu cliente con una visualización de alto impacto.",
        "ctaText": "Cotizar Renders",
        "whatsappNumber": "573132060072",
        "whatsappMessage": "Hola, quisiera cotizar renders"
    }
];

module.exports = { servicesData };
